# azure-pipelines.yml


trigger:
  branches:
    include:
      - main  # or master, depending on your default branch

pool:
  vmImage: 'ubuntu-latest'  # Choose an appropriate VM image

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'test'
